-- 코드를 입력하세요
# SELECT INFO.REST_ID, INFO.REST_NAME, INFO.FOOD_TYPE, INFO.FAVORITES, INFO.ADDRESS, ROUND(AVG(REVIEW.REVIEW_SCORE),2) AS REVIEW_SCORE
# FROM REST_INFO INFO, REST_REVIEW REVIEW
# WHERE INFO.REST_ID = REVIEW.REST_ID AND INFO.ADDRESS LIKE '서울%'
# GROUP BY INFO.REST_ID
# ORDER BY REVIEW_SCORE DESC, INFO.FAVORITES DESC;

SELECT INFO.REST_ID, INFO.REST_NAME, INFO.FOOD_TYPE, INFO.FAVORITES, INFO.ADDRESS, ROUND(AVG(REVIEW.REVIEW_SCORE), 2) AS REVIEW_SCORE
FROM REST_INFO INFO
JOIN REST_REVIEW REVIEW ON INFO.REST_ID = REVIEW.REST_ID
WHERE INFO.ADDRESS LIKE '서울%'
GROUP BY INFO.REST_ID, INFO.REST_NAME, INFO.FOOD_TYPE, INFO.FAVORITES, INFO.ADDRESS
ORDER BY REVIEW_SCORE DESC, INFO.FAVORITES DESC;

