-- 코드를 입력하세요
WITH USERJOIN AS (
    SELECT *
    FROM USER_INFO
    WHERE YEAR(JOINED) ='2021'
), PUCHASEDUSER AS (
    SELECT *
    FROM ONLINE_SALE
    WHERE USER_ID IN (SELECT USER_ID FROM USERJOIN)
)
SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, COUNT(DISTINCT PU.USER_ID) AS PUCHASED_USERS, ROUND(COUNT(DISTINCT PU.USER_ID)/(SELECT COUNT(USER_ID) FROM USERJOIN),1) AS PUCHASED_RATIO
FROM USERJOIN UJ, PUCHASEDUSER PU
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE)
ORDER BY YEAR(SALES_DATE), MONTH(SALES_DATE)