-- 코드를 입력하세요
# SELECT CAR_ID, AVAILABILITY =
#     CASE
#     WHEN (YEAR(START_DATE) ='2022' AND MONTH(START_DATE) <=10 AND DAY(START_DATE) <=15) AND (YEAR(END_DATE)='2022' AND MONTH(END_DATE)='10' AND DAY(END_DATE)>=16)
#     THEN AVAILABILITY ='대여중'
#     END
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# ORDER BY CAR_ID DESC;

SELECT CAR_ID,
	 if(sum(if('2022-10-16' BETWEEN START_DATE and END_DATE,'1','0'))=0,'대여 가능','대여중') AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY GROUP BY CAR_ID ORDER BY CAR_ID DESC;

# 대여중이지 않으면 대여가능이라고 생각해서 단순히 대여중인 값만 테이블에서 골라내고, 원본 테이블에서 대여중에 해당하는 CAR_ID에 해당하는 값들을 제외하고 골라내서 UNION함 
# 그래서 답은 똑같이 나오는데 오답이라고 함 ...
# WITH RENTING AS
# (
#     SELECT CAR_ID, '대여중' AS AVAILABILITY
#     FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
#     WHERE START_DATE <= '2022-10-16' AND
#           END_DATE >= '2022-10-16'
# )

# SELECT CAR_ID, '대여 가능' AS AVAILABILITY
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# WHERE CAR_ID NOT IN (
#     SELECT CAR_ID FROM RENTING)

# UNION 

# SELECT * FROM RENTING
# ORDER BY CAR_ID DESC