-- 코드를 입력하세요
WITH TEMP1 AS
(
SELECT MEMBER_ID AS MEMBER_ID1, COUNT(*) AS REVIEW_COUNT
FROM REST_REVIEW
GROUP BY MEMBER_ID
), TEMP2 AS (
    SELECT *
    FROM REST_REVIEW RR JOIN TEMP1 T1 ON RR.MEMBER_ID = T1.MEMBER_ID1
)
SELECT MP.MEMBER_NAME, T2.REVIEW_TEXT, DATE_FORMAT(T2.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE MP JOIN TEMP2 T2 ON MP.MEMBER_ID = T2.MEMBER_ID
WHERE T2.REVIEW_COUNT = (
    SELECT MAX(REVIEW_COUNT)
    FROM TEMP2
)
ORDER BY REVIEW_DATE, REVIEW_TEXT;