-- 코드를 입력하세요
WITH TEMP AS
(
    SELECT  CAR_ID, COUNT(*) AS RECORDS
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE DATE_FORMAT(START_DATE,'%Y-%m-%d') BETWEEN '2022-07%' AND '2022-10%'
    GROUP BY CAR_ID
    ORDER BY CAR_ID DESC
)
SELECT MONTH(CR.START_DATE) AS MONTH, CR.CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY CR JOIN TEMP T ON CR.CAR_ID = T.CAR_ID
WHERE DATE_FORMAT(CR.START_DATE,'%Y-%m-%d') BETWEEN '2022-07%' AND '2022-10%' AND CR.CAR_ID IN 
(SELECT CAR_ID
 FROM TEMP
 WHERE RECORDS>=5)
GROUP BY MONTH(CR.START_DATE),CR.CAR_ID
ORDER BY MONTH, CAR_ID DESC

# SELECT *
# FROM TEMP